#! /usr/bin/bash

if [ $# -lt 1 ]; then
        echo "numero de parametros incorreto."
        exit 0
fi

flags=""
if [ $# -gt 1 ]; then
        for i in $(seq 2 $#); do
                # echo "${!i}"
                flags="$flags -${!i}"
        done
        echo "compilacao feita com as seguintes flags: $flags"
fi


name=$(basename -s .c $1)
gcc $1 $flags -o $name
